### ISSUE TITLE
How Can I Get The File ‘Segmentation_Network.pkl’

### ISSUE THREAD

**Issue by NoUsernamePlea** [SJTU-mxtao/Semantic-Communication-Systems#6]
the python file address is 'semantic_extraction/VOC/main_semantic_encoding_diff_compre.py', in the line 451  
  has a statement 'model.load_state_dict(torch.load('Segmentation_Network.pkl'))'. I want to know how can I get the File ‘Segmentation_Network.pkl’

**Comment by Forest-Lee** [comment]
> the python file address is 'semantic_extraction/VOC/main_semantic_encoding_diff_compre.py', in the line 451 has a statement 'model.load_state_dict(torch.load('Segmentation_Network.pkl'))'. I want to know how can I get the File ‘Segmentation_Network.pkl’

Hi, I meet the same question, did you solved it and how? Could you please share your method?
